#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jun 11 23:18:11 GMT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a90bf657602e4579aa2fedaf0555494d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot top_assembler_tb_behav xil_defaultlib.top_assembler_tb -log elaborate.log"
xelab -wto a90bf657602e4579aa2fedaf0555494d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot top_assembler_tb_behav xil_defaultlib.top_assembler_tb -log elaborate.log

